### ISSUE TITLE
Post Legacy Source .tar.bz2 Files Under "Releases" On GitHub

### ISSUE THREAD

**Issue by TafThorne** [distcc/distcc#213]
A the end of #159 @afbjorklund the old source tarballs should posted for people to find.  That sounds like a good idea so I will try to go grab them and post them under the existing tags. 

Full quote: 
"Thanks for doing the tagging. If you want the source tarballs to be available, you need to upload those (after first doing a make dist, for the new releases). The old releases should use the old tarballs, so that the checksums match what people are expecting. The "dist" tarball has all the autotools stuff generated, unlike what you get when you clone from git. That is, so you don't have to run ./autogen.sh.

https://www.gnu.org/software/automake/manual/html_node/Dist.html

Old tarballs: https://code.google.com/archive/p/distcc/downloads
```
SHA1SUM

7564e4a4890ad6ff78ec0de620329b71179361e7  distcc-3.2rc1.tar.bz2
7cd46fe0926a3a859a516274e6ae59fa8ba0262d  distcc-3.2rc1.tar.gz
30663e8ff94f13c0553fbfb928adba91814e1b3a  distcc-3.1.tar.bz2
487ae2a73b0b1a0e6b240874319ca3ddda7287e8  distcc-3.1.tar.gz
```

**Comment by afbjorklund** [comment]
@TafThorne : It is not just legacy, for _every_ release you make you should put the result ("dist") up too!

I even question the value of having "source" tarballs, as one could just use git to get those as needed...
i.e. this one: https://github.com/distcc/distcc/archive/v3.2rc1.tar.gz (compared to [distcc-3.2rc1.tar.gz](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/distcc/distcc-3.2rc1.tar.gz))

But for the existing releases, it great if you put the _exact_ same files up so that the checksums match.

----

Do people still use .bz2 ? I thought if you wanted small you did .xz and if you wanted compatible you just went with good old .gz. Then again I suppose most people just do all three of them "just in case".

Like with the situation with the checksums and sha256/sha1/md5, more or less ? For this use case it doesn't really matter, just do what you are comfortable with (.tar.bz2). Using .tar.gz and MD5SUM works too.

**Comment by afbjorklund** [comment]
@TafThorne : It would probably also be good to start on some release documentation, like what needs to be done before a release ? Currently we have a couple of tests failing, because the `make distcheck` hasn't been run in a while... This is especially important when making _major_ changes like switching from `python` to `python3`! Not worth doing this in CI (i.e. Travis), but actual releases need some extra checks... ?

**Comment by TafThorne** [comment]
I'd love to know what needed to be done before a release.  With enough scrapping through old code and old web pages I am sure we can figure out a basic check list.

**Comment by shawnl** [comment]
I uploaded the 3.2rc1 tarballs
